#!/usr/bin/python


#kisel code proj


import os, subprocess, time

print("Приви, сисодмен! Я тибе памагу, лапа")
time.sleep(1)

COMMAND = "xinput"
PROCCES = subprocess.call(COMMAND.split())

ID_TABLET = input("\nУкадит айди планщета, коти/n")

COMMAND = "xinput {0} 1 1 1 1 1 1 1 1 1 1 1 1 1".format(ID_TABLET)
PROCCES = subprocess.call(COMMAND.split())

print("готово, пока, счастья и здоровья внуков красивых ну ты же идешь не будет на месте и в этом случае не предоставления документов не хватает времени не было как можно скорее в пятницу не будет на лайт бокс на сайте и мы не можем встретиться")
